config/routes.rb
Rails.application.routes.draw do

  #用户路由----------
  devise_for :users

  #前台专辑-文章路由----------
  resources :albums do
    member do
      post :like 
      post :unlike
    end
    resources :articles
    resources :reviews
  end

  #后台路由----------
  namespace :admin do

    # 后台专辑-文章路由
    resources :albums do
      resources :articles
    end

  end


  #首页路由----------
  root 'welcome#index'

end

app/models/album.rb
class Album < ApplicationRecord

  # 图片上传支持----------
  mount_uploader :album_cover, ImageUploader

  # 校验----------
  validates :title, presence: true

  # model关系----------
  belongs_to :user
  has_many :articles, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # 点赞多对多model关系----------
  has_many :likes, dependent: :destroy
  has_many :liked_users, :through => :likes, :source => :user

  def find_like(user)
    self.likes.where( :user_id => user.id).first
  end
  # ----------



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  # 图片上传支持----------
  mount_uploader :article_cover, ImageUploader

  # model关系----------
  belongs_to :user
  belongs_to :album


end

app/models/like.rb
class Like < ApplicationRecord
  # model关系----------
  belongs_to :user
  belongs_to :album
end

app/models/review.rb
class Review < ApplicationRecord

  # 校验----------
  validates :comment, presence: true

  # model关系----------
  belongs_to :user
  belongs_to :album

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   # model关系----------
   has_many :albums, dependent: :destroy
   has_many :articles, dependent: :destroy
   has_many :reviews, dependent: :destroy

   # 点赞多对多model关系----------
   has_many :likes, dependent: :destroy
   has_many :liked_albums, :through => :likes, :source => :album


   #email用户名简写
   def display_name
     self.email.split("@").first
   end


end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < AdminController
  before_action :only => [:new, :create, :update, :edit, :destroy]


  # CRUD----------
  def index
    @albums = Album.order("id DESC").all
  end

  def show
    @album = Album.find(params[:id])
    @articles = @album.order("id DESC").articles
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.user = current_user

    if @album.save
      redirect_to admin_albums_path
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to admin_albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
  end


  # private----------
  private

  def album_params
    params.require(:album).permit(:title, :description, :album_cover, :meta)
  end

end

app/controllers/admin/articles_controller.rb
class Admin::ArticlesController < AdminController
  before_action :only => [:new, :create, :update, :edit, :destroy]


  # CRUD----------
  def new
    @album = Album.find(params[:album_id])
    @article = Article.new
  end

  def create
    @album = Album.find(params[:album_id])
    @article = Article.new(article_params)
    @article.album = @album
    @article.user = current_user

    if @article.save
      redirect_to admin_albums_path
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:album_id])
    @article = Article.find(params[:id])
  end

  def update
    @album = Album.find(params[:album_id])
    @article = Article.find(params[:id])

    if @article.update(article_params)
      redirect_to admin_albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:album_id])
    @article = Article.find(params[:id])

    @article.destroy
  end


  # private----------
  private

  def article_params
    params.require(:article).permit(:title, :summary, :description, :label, :article_cover)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :require_admin!

  layout "admin"

  private

  # 管理员权限判断
  def require_admin!
    if current_user.role != "admin"
      flash[:alert] = "您的权限不足"
      redirect_to root_path
    end
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.order("id DESC").all
  end

  def show
    @album = Album.find(params[:id])
    @review = Review.new
  end

  # like点赞功能
  def like
    @album = Album.find(params[:id])
    unless @album.find_like(current_user)
      Like.create( :user => current_user, :album => @album )
    end
  end

  def unlike
    @album = Album.find(params[:id])
    like = @album.find_like(current_user)
    like.destroy

    render "like"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @album = Album.find(params[:album_id])
    @review.album_id = @album.id

    @review.save
  end

  private

  def review_params
    params.require(:review).permit(:comment, :user_id, :album_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @albums = Album.order("id DESC").all
  end

end

app/helpers/admin/albums_helper.rb
module Admin::AlbumsHelper
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/admin/albums/_form.html.erb
<%= simple_form_for [:admin, @album] do |f| %>
  <div class="form-group">
    <%= f.input :title, :label => "专辑名称" %>
    <%= f.input :meta, :label => "专辑标签" %>
    <%= f.cktext_area :description, as: :ckeditor, ckeditor: { toolbar: 'mini', language: "zh-CN" }, :label => "集序" %>
    <%= f.input :album_cover, as: :file, :label => "专辑封面" %>
  </div>
  <%= f.submit "提交", :class => "btn btn-sm btn-default", :data => { disable_with: "Submiting..." } %>
<% end %>

app/views/admin/albums/destroy.js.erb
$("#album-<%= @album.id %>").remove();

app/views/admin/albums/edit.html.erb
<div class="container">
  <h2>编辑专辑</h2>

  <%= render "form" %>

  <!-- 当前封面 -->
  <% if @album.album_cover.present? %>
    <span>当前封面</span>
    <%= image_tag(@album.album_cover.thumb.url) %>
  <% end %>
</div>

app/views/admin/albums/index.html.erb
<div class="container">
  <h2>所有专辑</h2>

  <div class="group">
    <%= link_to("新增专辑", new_admin_album_path, :class => "btn btn-primary pull-right") %>
  </div>


  <table class="table table-hover">
    <thead>
      <tr>
        <td>Cover</td>
        <td>Title</td>
        <td>Operation</td>
        <td>Articles</td>
      </tr>
    </thead>

    <tbody>
      <% @albums.each do |album| %>
        <tr id="album-<%= album.id %>">
          <td>
            <%= link_to album_path(album) do %>
              <% if album.album_cover.present? %>
                <%= image_tag(album.album_cover.mini.url, :class => "thumbnail") %>
              <% else %>
                <%= image_tag("http://placehold.it/50x50&text=No Pic", class:"thumbnail") %>
              <% end %>
            <% end %>
          </td>
          <td><%= album.title %></td>
          <td>
            <%= link_to("编辑", edit_admin_album_path(album), :class => "btn btn-xs btn-default") %>
            <%= link_to("删除", admin_album_path(album), method: :delete, :remote => true, :class => "btn btn-xs btn-default", data: { confirm: "确定删除?" }) %>
            <%= link_to("新增文章", new_admin_album_article_path(album), :class => "btn btn-xs btn-default") %>
          </td>
          <td>
            <% album.articles.each do |article| %>
              <div id="article-<%= article.id %>">
                <%= link_to(article.title, album_article_path(album, article)) %>
                <span>
                  <%= link_to("编辑", edit_admin_album_article_path(album, article), :class => "btn btn-xs btn-default") %>
                </span>
                <span>
                  <%= link_to("删除", admin_album_article_path(album, article), method: :delete, :remote => true, :class => "btn btn-xs btn-default", data: { confirm: "确定删除?" }) %>
                </span> <br>
              </div>
            <% end %>
          </td>
        </tr>
      <% end %>
    </tbody>

  </table>


</div>

app/views/admin/albums/new.html.erb
<div class="container">
  <h2>新增专辑</h2>

  <%= render "form" %>

</div>

app/views/admin/articles/_form.html.erb
<%= simple_form_for [:admin, @album, @article] do |f| %>
  <div class="form-group">
    <%= f.input :title, :label => "文章标题" %>
    <%= f.input :label, :label => "文章标签" %>
    <%= f.input :summary, :label => "摘要" %>
    <%= f.cktext_area :description, as: :ckeditor, ckeditor: { toolbar: 'mini', language: "zh-CN" }, :label => "文章内容" %>
    <%= f.input :article_cover, as: :file, :label => "文章封面" %>
  </div>
  <%= f.submit "提交", :class => "btn btn-sm btn-default", :data => { disable_with: "Submiting..." } %>
<% end %>

app/views/admin/articles/destroy.js.erb
$("#article-<%= @article.id %>").remove();

app/views/admin/articles/edit.html.erb
<div class="container">
  <h2>编辑文章</h2>

  <%= render "form" %>

  <!-- 当前封面 -->
  <% if @article.article_cover.present? %>
    <span>当前封面</span><br>
    <%= image_tag(@article.article_cover.thumb.url) %>
  <% end %>
</div>

app/views/admin/articles/new.html.erb
<div class="container">
  <h2>新增文章</h2>

  <%= render "form" %>

</div>

app/views/albums/_like.html.erb
<% if @album.liked_users.any? %>
  <%= @album.liked_users.map{ |u| u.display_name }.join(",") %> 点了赞
<% end %>

<% if current_user %>
  <% if @album.find_like(current_user) %>
    <%= link_to "-1", unlike_album_path(@album), :method => :post, :remote => true, :clase => "btn btn-default", :class => "btn btn-default" %>
  <% else %>
    <%= link_to "+1", like_album_path(@album), :method => :post, :remote => true, :clase => "btn btn-default", :class => "btn btn-default" %>
  <% end %>
<% end %>

app/views/albums/like.js.erb
str = "<%= j render :partial => "like", :locals => { :album => @album } %>";
$("#album-like-<%= @album.id %>").html(str);

app/views/albums/show.html.erb
<div class="container">
  <section class="row">

      <!-- album大标题 -->
      <section class="album-show-box col-md-10 col-md-offset-1 col-xs-12">

        <p>「<%= @album.meta %>」</p>
        <h1><%= @album.title %></h1>

        <div class="album-show-covor" style="
        background-image: url('<%= @album.album_cover.url %>') ;">
        </div>

      </section>

      <!-- album集序 -->
      <section class="album-info col-md-10 col-md-offset-1 col-xs-12">
        <h4 class="text-center">集序：</h4>

        <div class="album-description row img-responsive center-block">
          <%= sanitize @album.description %>
        </div>

        <!-- album作者 -->
        <!-- <div class="col-md-4 col-md-offset-4 text-center">
          <div class="album-user-avatar">
            <%= image_tag("http://placehold.it/100x100&text=No Pic", class: "img-responsive img-circle center-block")%>
          </div>
          <span>韵儿爸爸</span>
          <hr>
          <div class="album-user-info">
            <p class="center-block">如果你去观察就会发现，如今的市场上已经见不到那些只讲地段、板塔这些简单粗暴的产品，当企业开始深挖客户需求和痛点，开始不仅仅提供最基本的居住功能，而是转向更多附加值；</p>
          </div>
          <hr>
        </br>
        </div> -->

        <!-- album下的所有文章articles -->
        <div class="album-show-articles text-center col-xs-12">
          <% @album.articles.order("created_at DESC").each do |article| %>

            <%= link_to album_article_path(@album, article) do%>
              <section class="album-show-article-box">
                <h3><%= article.title %></h3>
                <section class="album-show-articles-summary">
                  <p><%= sanitize article.summary %></p>
                </section>
                <div class="article-cover" style="
                background-image: url('<%= article.article_cover.medium.url %>') ;">
                </div>
              </section>
            <% end %>

          <% end %>
        </div>


        <!-- like点赞 -->
        <div class="text-center">
          <span id="album-like-<%= @album.id %>">
            <%= render :partial => "like", :local => { :album => @album } %>
          </span>
        </div>


        <div class="container">
          <br>
        </div>
        <hr>
        <!-- 输入表单 -->
        <%= simple_form_for [@album, @review], :remote => true do |f| %>
          <div class="review-album-form">
            <%= f.input :comment, :label => "评论一下：" %>
          </div>
          <div class="container-fluid">
            <div class="row">
              <%= f.submit "提交", class: "btn btn-sm btn-default pull-right", data: { disable_with: "正在提交..." } %>
            </div>
          </div>
        <% end %>

        <!-- 评论列表 -->
        <div class="album-reviews">
        </br>
          <ul>
            <div id="album-review-list">
              <% @album.reviews.order("created_at DESC").each do |review| %>
                <%= render :partial => "reviews/review", :locals => { :review => review } %>
              <% end %>
            </div>
          </ul>
        </div>

      </section>

  </section>
</div>

app/views/articles/show.html.erb
<div class="container">
  <section class="row">

    <!-- article标题和meta -->
    <section class="article-show-box col-md-10 col-md-offset-1 col-xs-12">
      <h1><%= @article.title %></h1>

      <div class="row">
        <div class="col-xs-9">
          <p class="article-meta"><%= @article.user.display_name %> · <%= @article.label %> · <%= time_ago_in_words(@article.created_at) %>前 · 打开原文 </p>
        </div>

        <!-- 社群分享 -->
        <div class=" col-xs-3 text-right">
          <%= social_share_button_tag(@article.title, :allow_sites => %w(wechat weibo douban), :image => @article.article_cover.url , desc: @article.description) %>
        </div>
      </div>


      <div class="article-show-covor" style="
      background-image: url('<%= @article.article_cover.url %>') ;">
      </div>
    </section>

    <!-- article - description -->
    <section class="article-info col-md-10 col-md-offset-1 col-xs-12">

      <div class="article-description row img-responsive center-block">
        <%= sanitize @article.description %>
      </div>

    </section>

  </section>

</div>

app/views/reviews/_review.html.erb
<li id="review-<%= review.id %>">
  <div class="album-review-user-avatar row">
    <%= image_tag("http://placehold.it/30x30&text=No Pic", class: "img-responsive img-circle")%>
  </div>
  <span>韵儿爸爸 ·  <%= time_ago_in_words(review.created_at) %>前</span>

  <div class="album-review-comment">
    <%= sanitize review.comment %>
  </div>
</li>

app/views/reviews/create.js.erb
<% if @review.valid? %>
  $("#album-review-list").prepend("<%=j render :partial => "reviews/review", :locals => { :review => @review } %>");
  $("#review_comment").val("")
<% else %>
  alert("亲！评论不能为空哦！")
<% end %>

app/views/welcome/index.html.erb
<h2 id="message" class="to-landingpage text-center">
  我们为什么要做一个全栈客？
</h2>

<main class="great">

  <!-- 四个banner -->
  <ul class="container-fluid grid">
    <section class="row">
      <% @albums.each do |album| %>
        <li class="album-banner col-sm-6 col-xs-12" style="
        background-image: url('<%= album.album_cover.url %>') ;">

          <%= link_to album_path(album) do %>
            <div class="banner-album-box">
              <p>「<%= album.meta %>」</p>
              <h3><%= album.title %></h3>
              <div class="album-covor" style="
              background-image: url('<%= album.album_cover.thumb.url %>') ;">
              </div>
            </div>
          <% end %>
        </li>

      <% end %>
    </section>
  </ul>

  <!-- 最新简集 -->

  <div class="text-center"></br>
    <h2 class="category—name">热门简集</h2>

    <% @albums.each do |album| %>

      <%= link_to album_path(album) do %>
        <div class="album-box">
          <p>「<%= album.meta %>」</p>
          <h3><%= album.title %></h3>
          <div class="album-covor" style="
          background-image: url('<%= album.album_cover.thumb.url %>') ;">
          </div>
        </div>
      <% end %>

    <% end %>

  </div>

</main>