config/routes.rb
Rails.application.routes.draw do

  #用户路由----------
  devise_for :users

  #前台专辑-文章路由----------
  resources :albums do
    member do
      post :like 
      post :unlike
    end
    resources :articles
    resources :reviews
  end

  #后台路由----------
  namespace :admin do

    # 后台专辑-文章路由
    resources :albums do
      resources :articles
    end

  end


  #首页路由----------
  root 'welcome#index'

end

app/models/album.rb
class Album < ApplicationRecord

  # 图片上传支持----------
  mount_uploader :album_cover, ImageUploader

  # 校验----------
  validates :title, presence: true

  # model关系----------
  belongs_to :user
  has_many :articles, dependent: :destroy
  has_many :reviews, dependent: :destroy

  # 点赞多对多model关系----------
  has_many :likes, dependent: :destroy
  has_many :liked_users, :through => :likes, :source => :user

  def find_like(user)
    self.likes.where( :user_id => user.id).first
  end
  # ----------



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord

  # 图片上传支持----------
  mount_uploader :article_cover, ImageUploader

  # model关系----------
  belongs_to :user
  belongs_to :album


end

app/models/like.rb
class Like < ApplicationRecord
  # model关系----------
  belongs_to :user
  belongs_to :album
end

app/models/review.rb
class Review < ApplicationRecord

  # 校验----------
  validates :comment, presence: true

  # model关系----------
  belongs_to :user
  belongs_to :album

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

   # model关系----------
   has_many :albums, dependent: :destroy
   has_many :articles, dependent: :destroy
   has_many :reviews, dependent: :destroy

   # 点赞多对多model关系----------
   has_many :likes, dependent: :destroy
   has_many :liked_albums, :through => :likes, :source => :album


   #email用户名简写
   def display_name
     self.email.split("@").first
   end


end

app/controllers/admin/albums_controller.rb
class Admin::AlbumsController < AdminController
  before_action :only => [:new, :create, :update, :edit, :destroy]


  # CRUD----------
  def index
    @albums = Album.order("id DESC").all
  end

  def show
    @album = Album.find(params[:id])
    @articles = @album.order("id DESC").articles
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(album_params)
    @album.user = current_user

    if @album.save
      redirect_to admin_albums_path
    else
      render :new
    end
  end

  def edit
    @album = Album.find(params[:id])
  end

  def update
    @album = Album.find(params[:id])

    if @album.update(album_params)
      redirect_to admin_albums_path
    else
      render :edit
    end
  end

  def destroy
    @album = Album.find(params[:id])
    @album.destroy
  end


  # private----------
  private

  def album_params
    params.require(:album).permit(:title, :description, :album_cover, :meta)
  end

end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  protect_from_forgery with: :exception

  before_action :authenticate_user!
  before_action :require_admin!

  layout "admin"

  private

  # 管理员权限判断
  def require_admin!
    if current_user.role != "admin"
      flash[:alert] = "您的权限不足"
      redirect_to root_path
    end
  end

end

app/controllers/albums_controller.rb
class AlbumsController < ApplicationController

  def index
    @albums = Album.order("id DESC").all
  end

  def show
    @album = Album.find(params[:id])
    @review = Review.new
  end

  # like点赞功能
  def like
    @album = Album.find(params[:id])
    unless @album.find_like(current_user)
      Like.create( :user => current_user, :album => @album )
    end
  end

  def unlike
    @album = Album.find(params[:id])
    like = @album.find_like(current_user)
    like.destroy

    render "like"
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController

  def show
    @article = Article.find(params[:id])
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :authenticate_user!

  def new
    @review = Review.new
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @album = Album.find(params[:album_id])
    @review.album_id = @album.id

    @review.save
  end

  private

  def review_params
    params.require(:review).permit(:comment, :user_id, :album_id)
  end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

  def index
    @albums = Album.order("id DESC").all
  end

end

app/helpers/admin/albums_helper.rb
module Admin::AlbumsHelper
end

app/helpers/admin/articles_helper.rb
module Admin::ArticlesHelper
end

app/helpers/albums_helper.rb
module AlbumsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/common/_footer.html.erb
<div class="text-center">
  <br><br>
  <p>text</p>

</div>

app/views/common/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="/"><img src='<%= image_url 'logo.png' %>' ></a>
      <!-- 响应式导航 -->
      <button type="button" class="navbar-toggle"
              data-toggle="collapse"
              data-target=".navbar-ex1-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
    </div>

    <div class="navbar-collapse navbar-ex1-collapse collapse navbar-right" aria-expanded="false">
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to("浏览集册", albums_path) %></li>
        <% if !current_user %>
          <li><%= link_to("注册", new_user_registration_path, class: "navbar-font-size") %></li>
          <li><%= link_to("登入", new_user_session_path, class: "navbar-font-size") %></li>
        <% else %>
          <li class="dropdown navbar-font-size">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= current_user.display_name %>
              <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <% if current_user.role == "admin" %>
                <li> <%= link_to("管理员后台", admin_albums_path, class: "navbar-font-size") %> </li>
              <% end %>
              <li> <%= link_to("退出", destroy_user_session_path, method: :delete, class: "navbar-font-size") %> </li>
            </ul>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>简集|后台</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="content">

      <div class="container-fluid">
        <div class="row">
          <%= render "common/navbar" %>
        </div>

        <div class="row">
          <%= yield %>
        </div>
      </div>

    </div>

    <%= render "common/footer" %>

  </body>
</html>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>简集</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
    <div class="content">

      <div class="container-fluid">
        <div class="row">
          <%= render "common/navbar" %>
        </div>

        <div class="row">
          <%= yield %>
        </div>
      </div>

    </div>

    <%= render "common/footer" %>

  </body>
</html>